import React from "react";
import RoomBoard from "../components/Room-Board";
import ExtraVolunteersDish from "../components/Extra-Volunteers-Dish";
import { Grid, GridItem, Heading, IconButton } from "@chakra-ui/react";
import { ArrowRight, ArrowLeft, ArrowUp, MoveUpRight, MoveUpLeft } from "lucide-react";
import { GoQuestion, GoChevronDown, GoChevronUp } from "react-icons/go";
import { FiSettings } from "react-icons/fi";
import { useNavigate } from "react-router-dom";

function Game() {
  const navigate = useNavigate();
  return (
    <Grid 
      style={{ backgroundColor: "#622A2A", width: "100vw", height: "100vh"}}
      templateColumns="repeat(5, 1fr)"
      templateRows="repeat(4, 1fr)"
      position="relative">
        {/* Rules and Settings Button */}
        <GridItem
          padding={15}
          position={'absolute'}>
            <IconButton 
              aria-label="Rules"
              onClick={() => navigate("/rules")}
              rounded='full'
              size='xl'
              colorPalette="white">
                <GoQuestion/>
            </IconButton>
        </GridItem>
        <GridItem
          paddingTop={15}
          paddingLeft={1725}
          position={'absolute'}>
            <IconButton 
              aria-label="Settings"
              onClick={() => navigate("/settings")}
              rounded='full'
              size='xl'
              colorPalette="white">
                <FiSettings/>
            </IconButton>
        </GridItem>

        {/* Lunch and Lunch Arrows */}
        <GridItem 
          top={-81}
          paddingLeft={410}
          column={2} 
          row={1}
          position="fixed">
            <GoChevronDown
              size="225px" 
              color="white"/>
        </GridItem>
        <GridItem 
          paddingTop={115}
          column={1} 
          row={1}>
            <ArrowLeft 
              size="250px" 
              color="white"/>
        </GridItem>
        <GridItem
          paddingTop={75}
          column={2} 
          row={1}>
            <RoomBoard 
              width="450px" 
              height="300px">
                <Grid
                  templateColumns="repeat(10, 1fr)"
                  templateRows="repeat(4, 1fr)"
                  gap={3}>
                    <GridItem
                      left={450}
                      top={100}
                      position='absolute'>
                        <Heading
                          colorPalette='black'
                          size='5xl'>Lunch</Heading>
                    </GridItem>
                    <GridItem
                      gridRow={2}
                      gridColumn={2}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={2}
                      gridColumn={3}
                      justifyItems='center'>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={2}
                      gridColumn={4}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={2}
                      gridColumn={5}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={2}
                      gridColumn={6}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={2}
                      gridColumn={7}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={2}
                      gridColumn={8}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={2}
                      gridColumn={9}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={3}
                      gridColumn={2}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={3}
                      gridColumn={3}
                      justifyItems='center'>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={3}
                      gridColumn={4}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={3}
                      gridColumn={5}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={3}
                      gridColumn={6}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={3}
                      gridColumn={7}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={3}
                      gridColumn={8}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={3}
                      gridColumn={9}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={4}
                      gridColumn={2}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={4}
                      gridColumn={3}
                      justifyItems='center'>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={4}
                      gridColumn={4}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={4}
                      gridColumn={5}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={4}
                      gridColumn={6}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={4}
                      gridColumn={7}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={4}
                      gridColumn={8}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={4}
                      gridColumn={9}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                </Grid> 
                </RoomBoard>
        </GridItem>

        {/* Presentation and Presentation Arrows */}
        <GridItem 
          top={-81}
          paddingLeft={1160}
          column={2} 
          row={1}
          position="fixed">
            <GoChevronDown
              size="225px" 
              color="white"/>
        </GridItem>
        <GridItem 
          paddingTop={115}
          column={3} 
          row={1}>
            <ArrowLeft 
              size="250px" 
              color="white"/>
        </GridItem>
        <GridItem
          paddingTop={75}
          column={4} 
          row={1}>
            <RoomBoard 
              width="450px" 
              height="300px"> 
                <Grid
                  templateColumns="repeat(10, 1fr)"
                  templateRows="repeat(4, 1fr)"
                  gap={3}>
                    <GridItem
                      left={1125}
                      top={100}
                      position='absolute'>
                        <Heading
                          colorPalette='black'
                          size='5xl'>Presentation</Heading>
                    </GridItem>
                    <GridItem
                      gridRow={2}
                      gridColumn={2}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={2}
                      gridColumn={3}
                      justifyItems='center'>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={2}
                      gridColumn={4}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={2}
                      gridColumn={5}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={2}
                      gridColumn={6}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={2}
                      gridColumn={7}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={2}
                      gridColumn={8}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={2}
                      gridColumn={9}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={3}
                      gridColumn={2}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={3}
                      gridColumn={3}
                      justifyItems='center'>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={3}
                      gridColumn={4}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={3}
                      gridColumn={5}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={3}
                      gridColumn={6}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={3}
                      gridColumn={7}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={3}
                      gridColumn={8}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={3}
                      gridColumn={9}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={4}
                      gridColumn={2}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={4}
                      gridColumn={3}
                      justifyItems='center'>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={4}
                      gridColumn={4}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={4}
                      gridColumn={5}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                </Grid> </RoomBoard>
        </GridItem>
        <GridItem 
          paddingTop={115}
          column={5} 
          row={1}>
            <ArrowRight 
              size="250px" 
              color="white"/>
        </GridItem>

        {/* Diagonal Arrows */}
        <GridItem 
          position={'absolute'}
          colSpan={5}
          column={3} 
          row={2}
          paddingTop={320}
          paddingLeft={730}>
            <MoveUpRight 
              size="350px" 
              color="white"/>
        </GridItem>
        <GridItem 
          position={'absolute'}
          colSpan={5}
          column={3} 
          row={2}
          paddingTop={320}
          paddingLeft={700}>
            <MoveUpLeft 
              size="350px" 
              color="white"/>
        </GridItem>

        {/* Extra Volunteers */}
        <GridItem
          position={'absolute'}
          colSpan={5}
          column={2} 
          row={2}
          paddingTop={425}
          paddingLeft={325}>
          <ExtraVolunteersDish
            size="150px">
              <Heading
                size='2xl'>
                  Volunteers
              </Heading>
            </ExtraVolunteersDish>
        </GridItem>

        {/* Hour Box */}
        <GridItem
          position={'absolute'}
          colSpan={5}
          column={1} 
          row={2}
          paddingTop={370}
          paddingLeft={30}>
            <RoomBoard 
              width="200px" 
              height="300px"
              backgroundColor="black"> 
                <Grid
                  templateColumns="repeat(2, 1fr)"
                  templateRows="repeat(3, 1fr)"
                  alignItems="center"
                  justifyItems="center"
                  gap={3}>
                    <GridItem
                      column={1}
                      row={1}
                      colSpan={2}>
                      <Heading
                        colorPalette='black'
                        size='3xl'>
                          Hour
                      </Heading>
                    </GridItem>

                    {/* Red Box */}
                    <GridItem
                      column={1}
                      row={2}>
                        <RoomBoard 
                          width="80px" 
                          height="80px"
                          backgroundColor="red"> 
                            <Heading
                            colorPalette='black'
                            size='xl'>
                              1
                          </Heading>
                        </RoomBoard>
                    </GridItem>

                    {/* Blue Box */}
                    <GridItem
                      column={2}
                      row={2}>
                        <RoomBoard 
                          width="80px" 
                          height="80px"
                          backgroundColor="blue"> 
                            <Heading
                            colorPalette='black'
                            size='xl'>
                              2
                          </Heading>
                        </RoomBoard>
                    </GridItem>
                    {/* Green Box */}
                    <GridItem
                      column={1}
                      row={3}>
                        <RoomBoard 
                          width="80px" 
                          height="80px"
                          backgroundColor="green"> 
                            <Heading
                            colorPalette='black'
                            size='xl'>
                              3
                          </Heading>
                        </RoomBoard>
                    </GridItem>

                    {/* Purple Box */}
                    <GridItem
                      column={2}
                      row={3}>
                        <RoomBoard 
                          width="80px" 
                          height="80px"
                          backgroundColor="purple"> 
                            <Heading
                            colorPalette='black'
                            size='xl'>
                              4
                          </Heading>
                        </RoomBoard>
                    </GridItem>
                </Grid>
            </RoomBoard>
          </GridItem>
        
        {/* Welcome Session and Arrows */}
        <GridItem 
          paddingTop={290}
          column={1} 
          row={3}>
            <ArrowRight 
              size="250px" 
              color="white"/>
        </GridItem>
        <GridItem 
          paddingTop={380}
          paddingLeft={490}
          column={2} 
          row={2}
          position='absolute'>
            <ArrowUp 
              size="250px" 
              color="white"/>
        </GridItem>
        <GridItem
          paddingTop={250}
          column={2} 
          row={3}>
            <RoomBoard 
              width="450px" 
              height="300px">
                <Grid
                  templateColumns="repeat(10, 1fr)"
                  templateRows="repeat(4, 1fr)"
                  gap={3}>
                    <GridItem
                      paddingLeft={7}
                      top={650}
                      position='absolute'>
                        <Heading
                          colorPalette='black'
                          size='5xl'>Welcome Session</Heading>
                    </GridItem>
                    <GridItem
                      gridRow={2}
                      gridColumn={2}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={2}
                      gridColumn={3}
                      justifyItems='center'>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={2}
                      gridColumn={4}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={2}
                      gridColumn={5}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={2}
                      gridColumn={6}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={2}
                      gridColumn={7}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={2}
                      gridColumn={8}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={2}
                      gridColumn={9}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={3}
                      gridColumn={2}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={3}
                      gridColumn={3}
                      justifyItems='center'>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={3}
                      gridColumn={4}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={3}
                      gridColumn={5}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={3}
                      gridColumn={6}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={3}
                      gridColumn={7}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={3}
                      gridColumn={8}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={3}
                      gridColumn={9}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={4}
                      gridColumn={2}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={4}
                      gridColumn={3}
                      justifyItems='center'>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={4}
                      gridColumn={4}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={4}
                      gridColumn={5}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={4}
                      gridColumn={6}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={4}
                      gridColumn={7}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={4}
                      gridColumn={8}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      gridRow={4}
                      gridColumn={9}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                </Grid>  </RoomBoard>
        </GridItem>
        <GridItem 
          paddingTop={860}
          paddingLeft={410}
          column={2} 
          row={4}
          position="fixed">
            <GoChevronDown
              size="225px" 
              color="white"/>
        </GridItem>

        {/* Interview and Arrows */}
        <GridItem 
          paddingTop={380}
          paddingLeft={1150}
          column={2} 
          row={2}
          position='absolute'>
            <ArrowUp 
              size="250px" 
              color="white"/>
        </GridItem>
        <GridItem 
          paddingTop={290}
          column={3} 
          row={3}>
            <ArrowRight 
              size="250px" 
              color="white"/>
        </GridItem>
        <GridItem
          paddingTop={250}
          column={4} 
          row={3}>
            <RoomBoard 
              width="450px" 
              height="300px">
                <Grid
                  templateColumns="repeat(10, 1fr)"
                  templateRows="repeat(4, 1fr)"
                  position="fixed"
                  maxWidth='450px'
                  maxHeight='300px'
                  justifyContent='center'>
                    <GridItem
                      row={1}
                      column={5}
                      colSpan={10}
                      justifyItems='center'
                      paddingTop={30}>
                        <Heading
                          colorPalette='black'
                          size='5xl'>Interview</Heading>
                    </GridItem>
                    <GridItem
                      row={2}
                      column={2}
                      justifyItems='center'
                      paddingLeft={120}
                      paddingTop={50}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      row={2}
                      column={3}
                      justifyItems='center'
                      paddingLeft={25}
                      paddingTop={50}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      row={2}
                      column={4}
                      justifyItems='center'
                      paddingLeft={25}
                      paddingTop={50}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                    <GridItem
                      row={2}
                      column={5}
                      justifyItems='center'
                      paddingLeft={25}
                      paddingTop={50}>
                        <RoomBoard
                          width="35px"
                          height="35px"
                          backgroundColor="gray">
                        </RoomBoard>
                    </GridItem>
                </Grid>
            </RoomBoard>
        </GridItem>
        <GridItem 
          paddingTop={290}
          column={5} 
          row={3}>
            <ArrowRight 
              size="250px" 
              color="white"/>
        </GridItem>
        <GridItem 
          paddingTop={860}
          paddingLeft={1160}
          column={4} 
          row={4}
          position="fixed">
            <GoChevronUp
              size="225px" 
              color="white"/>
        </GridItem>
        
    </Grid>
  );
}

export default Game;
